import { StyleSheet } from 'react-native';
import { colors } from '../constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 4,
    paddingBottom: 12,
    backgroundColor: colors.background,
    borderBottomWidth: 0,
    borderBottomColor: colors.border,
  },
  headerRTL: {
    flexDirection: 'row-reverse',
  },
  menuButton: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 44,
    height: 44,
  },
  titleContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileButton: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 44,
    height: 44,
    borderRadius: 22,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: colors.primary,
    backgroundColor: colors.backgroundLight,
  },
  profileIcon: {
    width: '100%',
    height: '100%',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.primary,
    letterSpacing: 1,
  },
  headerTitleRTL: {
    textAlign: 'right',
  },
  centerContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
  },
  emptyText: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  scrollView: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  scrollViewContent: {
    flexGrow: 1,
    paddingBottom: 360,
  },
  cartCard: {
    backgroundColor: colors.backgroundLight,
    borderRadius: 12,
    padding: 10,
    marginBottom: 12,
    position: 'relative',
    borderColor: colors.border,
  },
  oldBookingBadge: {
    position: 'absolute',
    top: 12,
    backgroundColor: '#FF6B6B',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    zIndex: 5,
  },
  oldBookingBadgeLTR: {
    right: 12,
    left: undefined,
  },
  oldBookingBadgeRTL: {
    left: 12,
    right: undefined,
  },
  oldBookingText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
  },
  removeIconButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    zIndex: 10,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeButtonRTL: {
    right: 'auto',
    left: 12,
  },
  itemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  itemHeaderRTL: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
  },
  itemImage: {
    width: 45,
    height: 45,
    borderRadius: 6,
    marginRight: 12,
  },
  itemImageRTL: {
    marginRight: 0,
    marginLeft: 12,
  },
  itemHeaderText: {
    flex: 1,
    justifyContent: 'center',
  },
  itemHeaderTextRTL: {
    alignItems: 'flex-end',
  },
  itemName: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textDark,
    marginBottom: 2,
  },
  itemNameRTL: {
    textAlign: 'right',
  },
  vendorName: {
    fontSize: 11,
    color: colors.textSecondary,
    marginBottom: 4,
  },
  vendorNameRTL: {
    textAlign: 'right',
  },
  itemQty: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  dateTimeSection: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: '#F9F9F9',
    borderRadius: 8,
    marginBottom: 6,
  },
  dateTimeSectionRTL: {
    flexDirection: 'row-reverse',
  },
  dateTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  dateTimeRowRTL: {
    flexDirection: 'row-reverse',
  },
  dateTimeText: {
    fontSize: 12,
    color: colors.textDark,
    fontWeight: '500',
  },
  priceSection: {
    paddingVertical: 2,
    marginBottom: 6,
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 3,
  },
  priceRowRTL: {
    flexDirection: 'row-reverse',
  },
  priceLabel: {
    fontSize: 11,
    color: colors.textDark,
    fontWeight: '500',
  },
  priceValue: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.primary,
  },
  deliveryChargeValue: {
    fontSize: 12,
    fontWeight: '700',
    color: '#28A745',
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  deleteButton: {
    width: 36,
    height: 36,
    backgroundColor: '#FFF5F5',
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#FFDDDD',
  },
  viewDetailsButton: {
    flex: 1,
    backgroundColor: colors.primary,
    borderRadius: 10,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewDetailsText: {
    color: colors.textWhite,
    fontSize: 12,
    fontWeight: '600',
  },
  editButton: {
    paddingHorizontal: 20,
    backgroundColor: '#F0F0F0',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  totalsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  totalRowFinal: {
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    paddingTop: 12,
    marginTop: 6,
  },
  totalLabel: {
    fontSize: 14,
    color: colors.textDark,
    fontWeight: '500',
  },
  totalLabelFinal: {
    fontSize: 15,
    color: colors.textDark,
    fontWeight: '700',
  },
  totalValue: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
  },
  totalValueGreen: {
    fontSize: 14,
    fontWeight: '700',
    color: '#28A745',
  },
  totalValueFinal: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.primary,
  },
  bottomSummary: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.backgroundLight,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    shadowColor: 'transparent',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
  },
  summaryRowTotal: {
    marginBottom: 8,
  },
  summaryLabel: {
    fontSize: 12,
    color: colors.textDark,
    fontWeight: '500',
  },
  summaryLabelTotal: {
    fontSize: 13,
    color: colors.textDark,
    fontWeight: '700',
  },
  summaryValue: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
  summaryValueGreen: {
    fontSize: 13,
    fontWeight: '700',
    color: '#00B383',
  },
  summaryValueTotal: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
  },
  divider: {
    height: 1,
    backgroundColor: '#D0D0D0',
    marginVertical: 8,
  },
  couponContainer: {
    marginBottom: 8,
  },
  couponInputRow: {
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
    position: 'relative',
  },
  couponInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#D0D0D0',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
    paddingRight: 40,
    fontSize: 12,
    color: colors.textDark,
    backgroundColor: '#FFFFFF',
  },
  couponInputRTL: {
    textAlign: 'right',
    paddingRight: 12,
    paddingLeft: 50,
  },
  couponStatusIcon: {
    position: 'absolute',
    right: 100,
    alignItems: 'center',
    justifyContent: 'center',
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'transparent',
  },
  couponStatusIconRTL: {
    right: 'auto',
    left: 10,
  },
  successIcon: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#4CAF50',
  },
  errorIcon: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#F44336',
  },
  applyButton: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 7,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 64,
  },
  applyButtonDisabled: {
    backgroundColor: colors.textSecondary,
    opacity: 0.5,
  },
  applyButtonText: {
    color: colors.textWhite,
    fontSize: 12,
    fontWeight: '700',
  },
  removeCouponButton: {
    backgroundColor: '#FF6B6B',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 7,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 64,
  },
  removeButtonText: {
    color: colors.textWhite,
    fontSize: 12,
    fontWeight: '700',
  },
  couponSuccessContainer: {
    backgroundColor: '#E8F5E9',
    borderRadius: 8,
    padding: 10,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#4CAF50',
  },
  couponSuccessText: {
    color: '#2E7D32',
    fontSize: 12,
    fontWeight: '600',
  },
  couponErrorContainer: {
    backgroundColor: '#FFEBEE',
    borderRadius: 8,
    padding: 10,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#F44336',
  },
  couponErrorText: {
    color: '#C62828',
    fontSize: 12,
    fontWeight: '600',
  },
  discountRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
  },
  discountLabel: {
    fontSize: 12,
    color: '#4CAF50',
    fontWeight: '600',
  },
  discountValue: {
    fontSize: 13,
    fontWeight: '700',
    color: '#4CAF50',
  },
  paymentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
  },
  paymentLabel: {
    fontSize: 12,
    color: colors.textDark,
    fontWeight: '600',
  },
  paymentValue: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textDark,
  },
  paymentLabelOrange: {
    fontSize: 12,
    color: '#FF8C00',
    fontWeight: '600',
  },
  paymentValueOrange: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FF8C00',
  },
  checkoutButton: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    marginBottom: 6,
  },
  checkoutButtonDisabled: {
    backgroundColor: colors.textSecondary,
    opacity: 0.6,
  },
  checkoutButtonText: {
    color: colors.textWhite,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  continueShoppingButton: {
    backgroundColor: '#00695C',
    borderRadius: 10,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  continueShoppingButtonText: {
    color: colors.textWhite,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  optionsContainer: {
    marginTop: 6,
    paddingHorizontal: 4,
  },
  optionsContainerRTL: {
    alignItems: 'flex-end',
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 3,
  },
  optionRowRTL: {
    flexDirection: 'row-reverse',
  },
  optionBullet: {
    fontSize: 12,
    color: colors.primary,
    marginRight: 6,
    lineHeight: 16,
  },
  optionBulletRTL: {
    marginRight: 0,
    marginLeft: 6,
  },
  optionText: {
    fontSize: 11,
    color: colors.textDark,
    lineHeight: 16,
    flex: 1,
  },
  optionTextRTL: {
    textAlign: 'right',
  },
  optionLabel: {
    fontWeight: '600',
    color: colors.textDark,
  },
  optionValue: {
    color: colors.textSecondary,
  },
  optionPrice: {
    color: colors.primary,
    fontWeight: '600',
  },
  swipeCardWrapper: {
    marginBottom: 12,
    position: 'relative',
  },
  swipeDeleteBehind: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    right: 0,
    width: 70,
    backgroundColor: '#FF4B4B',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    opacity: 0,
  },
  swipeDeleteBehindRTL: {
    right: undefined,
    left: 0,
  },
  infoDropdown: {
    position: 'absolute',
    top: 42,
    left: 8,
    right: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(0, 161, 156, 0.18)',
    zIndex: 1000,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 8,
  },
  infoDropdownRTL: {},
  infoDropdownTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.primary,
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 161, 156, 0.1)',
    paddingBottom: 4,
  },
  infoDropdownTitleRTL: {
    textAlign: 'right',
  },
  infoDropdownRow: {
    flexDirection: 'row',
    marginBottom: 6,
    width: '100%',
    alignItems: 'flex-start',
  },
  infoDropdownRowRTL: {
    flexDirection: 'row-reverse',
  },
  infoDropdownRowText: {
    fontSize: 11,
    color: colors.textDark,
    marginBottom: 6,
    textAlign: 'left',
  },
  infoDropdownRowTextRTL: {
    textAlign: 'right',
  },
  infoDropdownLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textDark,
    width: 100,
  },
  infoDropdownLabelRTL: {
    textAlign: 'right',
    marginLeft: 8,
  },
  infoDropdownValue: {
    fontSize: 11,
    color: colors.textSecondary,
    lineHeight: 14,
    flex: 1,
  },
  infoDropdownValueRTL: {
    textAlign: 'right',
  },
  backButton: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(0, 161, 156, 0.1)',
  },
  emptyContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  emptyTopSection: {
    height: 260,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.background,
    paddingTop: 30,
  },
  emptyBasketWrapper: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  curveContainer: {
    height: 60,
    backgroundColor: colors.background,
  },
  curveSvg: {
    width: '100%',
    height: '100%',
  },
  emptyBottomSection: {
    flex: 1,
    backgroundColor: colors.primary,
    alignItems: 'center',
    paddingHorizontal: 30,
    paddingTop: 10,
  },
  emptyTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 16,
    letterSpacing: 0.5,
  },
  emptySubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.85)',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 40,
  },
  emptyCtaButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 40,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
  },
  emptyCtaText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: colors.primaryDark,
    letterSpacing: 0.8,
  },
  loginFullPageContainer: {
    flex: 1,
    backgroundColor: colors.backgroundCard,
    position: 'relative',
  },
  loginScrollContainer: {
    flex: 1,
  },
  loginContentContainer: {
    paddingTop: 0,
    paddingBottom: 80,
  },
  loginHeaderBlock: {
    height: 140,
    backgroundColor: colors.primary,
    position: 'relative',
    overflow: 'hidden',
  },
  loginTopographicSvg: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  loginOverlayBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    backgroundColor: 'transparent',
    zIndex: 1,
  },
  loginOverlayBarRTL: {
    flexDirection: 'row-reverse',
  },
  loginBackButtonCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loginHeaderSpacer: {
    width: 40,
  },
  loginCurveDivider: {
    height: 40,
    backgroundColor: colors.primary,
    marginTop: -1,
  },
  loginPromptContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 30,
    paddingTop: 0,
  },
  loginPlaceholderCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#FFFFFF',
    marginTop: -50,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  loginPlaceholderIcon: {
    width: 50,
    height: 50,
    tintColor: colors.primary,
  },
  loginPromptTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.primaryDark,
    marginTop: 20,
    marginBottom: 12,
  },
  loginPromptTitleRTL: {
    fontFamily: 'System',
  },
  loginPromptText: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: 30,
  },
  loginPromptTextRTL: {
    fontFamily: 'System',
  },
  loginSubmitButton: {
    backgroundColor: colors.primary,
    height: 46,
    justifyContent: 'center',
    paddingHorizontal: 40,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  loginSubmitButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
});
