import { StyleSheet, Dimensions } from 'react-native';
import { colors } from '../constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 4,
    paddingBottom: 12,
    backgroundColor: colors.backgroundHome,
    borderBottomWidth: 0,
    borderBottomColor: 'transparent',
  },
  menuButton: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 44,
    height: 44,
  },
  titleContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileButton: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 44,
    height: 44,
    borderRadius: 22,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: colors.primary,
    backgroundColor: '#F5F5F5',
  },
  profileIcon: {
    width: '100%',
    height: '100%',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.primary,
    letterSpacing: 1,
  },
  headerTitleRTL: {
    textAlign: 'right',
  },
  centerContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
  },
  emptyText: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  scrollView: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: Dimensions.get('window').width >= 600 ? 320 : 16,
  },
  cartCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    position: 'relative',
  },
  oldBookingBadge: {
    position: 'absolute',
    top: 12,
    left: 12,
    backgroundColor: '#FF6B6B',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    zIndex: 5,
  },
  oldBookingText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
  },
  removeButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    zIndex: 10,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeButtonRTL: {
    right: 'auto',
    left: 12,
  },
  itemHeader: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  itemHeaderRTL: {
    flexDirection: 'row-reverse',
  },
  itemImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 12,
  },
  itemImageRTL: {
    marginRight: 0,
    marginLeft: 12,
  },
  itemHeaderText: {
    flex: 1,
    justifyContent: 'center',
  },
  itemHeaderTextRTL: {
    alignItems: 'flex-end',
  },
  itemName: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.textDark,
    marginBottom: 4,
  },
  itemNameRTL: {
    textAlign: 'right',
  },
  vendorName: {
    fontSize: 12,
    color: colors.textSecondary,
    marginBottom: 6,
  },
  vendorNameRTL: {
    textAlign: 'right',
  },
  itemQty: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  dateTimeSection: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 12,
    paddingHorizontal: 8,
    backgroundColor: '#F9F9F9',
    borderRadius: 8,
    marginBottom: 12,
  },
  dateTimeSectionRTL: {
    flexDirection: 'row-reverse',
  },
  dateTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  dateTimeRowRTL: {
    flexDirection: 'row-reverse',
  },
  dateTimeText: {
    fontSize: 12,
    color: colors.textDark,
    fontWeight: '500',
  },
  priceSection: {
    paddingVertical: 8,
    marginBottom: 12,
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  priceLabel: {
    fontSize: 13,
    color: colors.textDark,
    fontWeight: '500',
  },
  priceValue: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
  },
  deliveryChargeValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#28A745',
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  deleteButton: {
    width: 44,
    height: 44,
    backgroundColor: '#FFF5F5',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#FFDDDD',
  },
  viewDetailsButton: {
    flex: 1,
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewDetailsText: {
    color: colors.textWhite,
    fontSize: 13,
    fontWeight: '600',
  },
  editButton: {
    paddingHorizontal: 20,
    backgroundColor: '#F0F0F0',
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  totalsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  totalRowFinal: {
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    paddingTop: 12,
    marginTop: 6,
  },
  totalLabel: {
    fontSize: 14,
    color: colors.textDark,
    fontWeight: '500',
  },
  totalLabelFinal: {
    fontSize: 15,
    color: colors.textDark,
    fontWeight: '700',
  },
  totalValue: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
  },
  totalValueGreen: {
    fontSize: 14,
    fontWeight: '700',
    color: '#28A745',
  },
  totalValueFinal: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.primary,
  },
  bottomSummary: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 10,
    paddingBottom: Dimensions.get('window').width >= 600 ? 140 : 14,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    shadowColor: 'transparent',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
  },
  summaryRowTotal: {
    marginBottom: 8,
  },
  summaryLabel: {
    fontSize: 12,
    color: colors.textDark,
    fontWeight: '500',
  },
  summaryLabelTotal: {
    fontSize: 13,
    color: colors.textDark,
    fontWeight: '700',
  },
  summaryValue: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
  summaryValueGreen: {
    fontSize: 13,
    fontWeight: '700',
    color: '#00B383',
  },
  summaryValueTotal: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
  },
  divider: {
    height: 1,
    backgroundColor: '#D0D0D0',
    marginVertical: 8,
  },
  couponContainer: {
    marginBottom: 12,
  },
  couponInputRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    position: 'relative',
  },
  couponInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#D0D0D0',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    paddingRight: 50,
    fontSize: 14,
    color: colors.textDark,
    backgroundColor: '#FFFFFF',
  },
  couponInputRTL: {
    textAlign: 'right',
    paddingRight: 12,
    paddingLeft: 50,
  },
  couponStatusIcon: {
    position: 'absolute',
    right: 90,
    alignItems: 'center',
    justifyContent: 'center',
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'transparent',
  },
  successIcon: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#4CAF50',
  },
  errorIcon: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#F44336',
  },
  applyButton: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 80,
  },
  applyButtonDisabled: {
    backgroundColor: colors.textSecondary,
    opacity: 0.5,
  },
  applyButtonText: {
    color: colors.textWhite,
    fontSize: 13,
    fontWeight: '700',
  },
  removeButton: {
    backgroundColor: '#FF6B6B',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 80,
  },
  removeButtonText: {
    color: colors.textWhite,
    fontSize: 13,
    fontWeight: '700',
  },
  couponSuccessContainer: {
    backgroundColor: '#E8F5E9',
    borderRadius: 8,
    padding: 10,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#4CAF50',
  },
  couponSuccessText: {
    color: '#2E7D32',
    fontSize: 12,
    fontWeight: '600',
  },
  couponErrorContainer: {
    backgroundColor: '#FFEBEE',
    borderRadius: 8,
    padding: 10,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#F44336',
  },
  couponErrorText: {
    color: '#C62828',
    fontSize: 12,
    fontWeight: '600',
  },
  discountRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
  },
  discountLabel: {
    fontSize: 12,
    color: '#4CAF50',
    fontWeight: '600',
  },
  discountValue: {
    fontSize: 13,
    fontWeight: '700',
    color: '#4CAF50',
  },
  paymentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
  },
  paymentLabel: {
    fontSize: 12,
    color: colors.textDark,
    fontWeight: '600',
  },
  paymentValue: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textDark,
  },
  paymentLabelOrange: {
    fontSize: 12,
    color: '#FF8C00',
    fontWeight: '600',
  },
  paymentValueOrange: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FF8C00',
  },
  checkoutButton: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    marginBottom: 6,
  },
  checkoutButtonDisabled: {
    backgroundColor: colors.textSecondary,
    opacity: 0.6,
  },
  checkoutButtonText: {
    color: colors.textWhite,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  continueShoppingButton: {
    backgroundColor: '#00695C',
    borderRadius: 8,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  continueShoppingButtonText: {
    color: colors.textWhite,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
});
