import { StyleSheet, Dimensions } from 'react-native';
import { colors } from '../constants/colors';

const { } = Dimensions.get('window');

export const myEventsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingVertical: 16,
    backgroundColor: colors.primary,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backButton: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  backIcon: {
    fontSize: 37,
    color: colors.textWhite,
    fontWeight: '700',
    lineHeight: 37,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.textWhite,
  },
  placeholder: {
    width: 40,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: colors.textSecondary,
  },
  filterSection: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 12,
  },
  dateFilterButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.textWhite,
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    minHeight: 44,
  },
  dateFilterText: {
    fontSize: 14,
    color: colors.primary,
    flex: 1,
    flexShrink: 1,
  },
  occasionFilterButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.textWhite,
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    minHeight: 44,
  },
  occasionFilterText: {
    fontSize: 14,
    color: colors.primary,
    flex: 1,
    flexShrink: 1,
  },
  filterContainer: {
    maxHeight: 60,
    marginBottom: 16,
    paddingVertical: 8,
  },
  filterContent: {
    paddingHorizontal: 16,
    gap: 8,
    alignItems: 'center',
  },
  filterButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: colors.backgroundLight,
    marginRight: 8,
    minWidth: 70,
    alignItems: 'center',
    justifyContent: 'center',
    height: 40,
  },
  filterButtonActive: {
    backgroundColor: colors.primary,
  },
  filterButtonText: {
    fontSize: 13,
    color: colors.textDark,
    fontWeight: '600',
    textAlign: 'center',
  },
  filterButtonTextActive: {
    color: colors.textWhite,
    fontWeight: '700',
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: colors.primaryDark,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  tableHeaderText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textWhite,
  },
  dateColumn: {
    flex: 0.3,
  },
  occasionColumn: {
    flex: 0.5,
  },
  actionColumn: {
    flex: 0.2,
    textAlign: 'right',
  },
  listContent: {
    paddingBottom: 20,
  },
  eventCard: {
    backgroundColor: colors.backgroundLight,
    marginHorizontal: 16,
    marginVertical: 8,
    borderRadius: 8,
    padding: 16,
  },
  eventHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  eventInfo: {
    flex: 1,
    flexDirection: 'row',
    gap: 16,
  },
  eventDate: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.primaryDark,
    minWidth: 80,
  },
  eventDetails: {
    flex: 1,
  },
  eventTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.primaryDark,
    marginBottom: 4,
  },
  eventVendor: {
    fontSize: 14,
    color: colors.primary,
    fontWeight: '500',
  },
  menuButton: {
    padding: 4,
    width: 30,
    alignItems: 'center',
  },
  menuIcon: {
    fontSize: 24,
    color: colors.textDark,
    fontWeight: '700',
  },
  menuDropdown: {
    marginTop: 12,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e8e8e8',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
    overflow: 'hidden',
  },
  menuItem: {
    paddingVertical: 14,
    paddingHorizontal: 20,
    backgroundColor: '#ffffff',
  },
  menuItemText: {
    fontSize: 15,
    color: colors.textDark,
    fontWeight: '500',
  },
  menuDivider: {
    height: 1,
    backgroundColor: '#f0f0f0',
    marginHorizontal: 16,
  },
  guestInfo: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  guestName: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textDark,
    marginBottom: 4,
  },
  guestContact: {
    fontSize: 12,
    color: colors.textSecondary,
    marginBottom: 4,
  },
  guestDate: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
  },
  emptyText: {
    fontSize: 16,
    color: colors.textSecondary,
  },
  clearButton: {
    marginLeft: 8,
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    borderRadius: 12,
  },
  clearButtonText: {
    fontSize: 14,
    color: '#ffffff',
    fontWeight: '700',
    lineHeight: 14,
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: '70%',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.primaryDark,
    marginBottom: 16,
    textAlign: 'center',
  },
  occasionList: {
    maxHeight: 300,
  },
  occasionItem: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  occasionItemText: {
    fontSize: 16,
    color: colors.textDark,
  },
  modalCloseButton: {
    marginTop: 16,
    backgroundColor: colors.primary,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  modalCloseButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  guestListContainer: {
    maxHeight: 400,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#f5f5f5',
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    marginTop: 12,
  },
  guestListItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  // guestInfo: {
  //   flex: 1,
  //   marginRight: 12,
  // },
  // guestName: {
  //   fontSize: 16,
  //   fontWeight: '600',
  //   color: colors.primaryDark,
  //   marginBottom: 4,
  // },
  guestPhone: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  guestListName: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.primaryDark,
    marginBottom: 4,
  },
  guestListEmail: {
    fontSize: 13,
    color: colors.textDark,
    marginBottom: 2,
  },
  guestListPhone: {
    fontSize: 13,
    color: colors.textSecondary,
    marginBottom: 2,
  },
  guestListDate: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  deleteGuestButton: {
    backgroundColor: '#dc3545',
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteGuestButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  emptyGuestList: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  emptyGuestText: {
    fontSize: 16,
    color: colors.textSecondary,
  },
  guestPageContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  guestPageContent: {
    flex: 1,
    backgroundColor: '#f5f5f5',
    marginTop: 50,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  guestPageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  guestPageBackButton: {
    padding: 8,
    width: 40,
  },
  guestPageBackIcon: {
    fontSize: 24,
    color: colors.primaryDark,
  },
  guestPageTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.primaryDark,
    flex: 1,
    textAlign: 'center',
  },
  guestPageScroll: {
    flex: 1,
    padding: 16,
  },
  guestPageCard: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  guestPageCardContent: {
    padding: 16,
  },
  guestPageInfo: {
    marginBottom: 12,
  },
  guestPageName: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.primaryDark,
    marginBottom: 4,
  },
  guestPageId: {
    fontSize: 12,
    color: colors.textSecondary,
    marginBottom: 8,
  },
  guestPageEmail: {
    fontSize: 14,
    color: colors.textDark,
    marginBottom: 4,
  },
  guestPagePhone: {
    fontSize: 14,
    color: colors.textDark,
  },
  removeButton: {
    backgroundColor: '#dc3545',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 6,
    alignSelf: 'flex-end',
  },
  removeButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  emptyGuestsContainer: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  emptyGuestsText: {
    fontSize: 16,
    color: colors.textSecondary,
  },
  // Simple action buttons styles
  actionButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  simpleActionButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 6,
  },
  simpleActionButtonText: {
    fontSize: 13,
    fontWeight: '500',
    color: colors.primary,
    textAlign: 'center',
  },
});
