import { StyleSheet, Dimensions } from 'react-native';
import { colors } from '../constants/colors';

const {} = Dimensions.get('window');

export const myEventsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    position: 'relative',
  },
  profileHeaderBlock: {
    height: 50,
    backgroundColor: colors.primary,
    position: 'relative',
    overflow: 'hidden',
  },
  topographicSvg: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  profileCurveDivider: {
    height: 30,
    backgroundColor: colors.primary,
    marginTop: -1,
  },
  headerOverlayBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    backgroundColor: 'transparent',
    zIndex: 1,
  },
  headerOverlayBarRTL: {
    flexDirection: 'row-reverse',
  },
  headerBackButtonCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 19,
    fontWeight: '700',
    color: colors.textWhite,
    flex: 1,
    textAlign: 'center',
  },
  headerTitleRTL: {
    fontFamily: 'System',
  },
  headerSpacer: {
    width: 40,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: colors.textSecondary,
  },
  filterSection: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 12,
  },
  dateFilterButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.textWhite,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 44,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  dateFilterText: {
    fontSize: 14,
    color: '#475569',
    flex: 1,
    fontWeight: '500',
    textAlign: 'left',
  },
  occasionFilterButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.textWhite,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 44,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  occasionFilterText: {
    fontSize: 14,
    color: '#475569',
    flex: 1,
    fontWeight: '500',
    textAlign: 'left',
  },
  filterContainer: {
    maxHeight: 52,
    marginBottom: 12,
    paddingVertical: 4,
    backgroundColor: 'transparent',
  },
  filterContent: {
    paddingHorizontal: 16,
    gap: 8,
    alignItems: 'center',
  },
  filterButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    height: 38,
    minWidth: 75,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  filterButtonActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  filterButtonText: {
    fontSize: 13,
    color: colors.textSecondary,
    fontWeight: '600',
    textAlign: 'center',
  },
  filterButtonTextActive: {
    color: colors.textWhite,
    fontWeight: '700',
  },
  tableHeader: {
    display: 'none', // Hidden to match modern card style
  },
  tableHeaderText: {
    fontSize: 12,
  },
  dateColumn: {
    flex: 1,
  },
  occasionColumn: {
    flex: 1,
  },
  actionColumn: {
    flex: 1,
  },
  listContent: {
    paddingBottom: 140,
    paddingTop: 8,
  },
  eventCard: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginVertical: 6,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  eventHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  eventMainInfo: {
    flex: 1,
    alignItems: 'flex-start',
  },
  eventTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.primaryDark,
    marginBottom: 4,
    textAlign: 'left',
  },
  eventVendor: {
    fontSize: 13,
    color: colors.textSecondary,
    fontWeight: '500',
    textAlign: 'left',
  },
  eventVendorName: {
    color: colors.primary,
    fontWeight: '600',
  },
  menuButton: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  eventMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 10,
  },
  eventDateBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0FDFA',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    gap: 4,
  },
  eventDateText: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: '600',
  },
  guestCountBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    gap: 4,
  },
  guestCountText: {
    fontSize: 12,
    color: '#475569',
    fontWeight: '600',
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusText: {
    fontSize: 11,
    fontWeight: '700',
  },
  menuIcon: {
    fontSize: 24,
    color: colors.textDark,
    fontWeight: '700',
  },
  menuDropdown: {
    position: 'absolute',
    zIndex: 999,
    width: 175,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    overflow: 'hidden',
  },
  menuItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#ffffff',
  },
  menuItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  menuItemContentRTL: {
    flexDirection: 'row-reverse',
  },
  menuItemText: {
    fontSize: 14,
    color: '#334155',
    fontWeight: '500',
    textAlign: 'left',
  },
  menuItemTextRTL: {
    textAlign: 'right',
    fontFamily: 'System',
  },
  menuDivider: {
    height: 1,
    backgroundColor: '#f1f5f9',
  },
  guestInfo: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  guestName: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textDark,
    marginBottom: 4,
  },
  guestContact: {
    fontSize: 12,
    color: colors.textSecondary,
    marginBottom: 4,
  },
  guestDate: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
  },
  emptyText: {
    fontSize: 16,
    color: colors.textSecondary,
  },
  clearButton: {
    marginLeft: 8,
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    borderRadius: 12,
  },
  clearButtonText: {
    fontSize: 14,
    color: '#ffffff',
    fontWeight: '700',
    lineHeight: 14,
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: '70%',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.primaryDark,
    marginBottom: 16,
    textAlign: 'center',
  },
  occasionList: {
    maxHeight: 300,
  },
  occasionItem: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  occasionItemText: {
    fontSize: 16,
    color: colors.textDark,
  },
  modalCloseButton: {
    marginTop: 16,
    backgroundColor: colors.primary,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  modalCloseButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  guestListContainer: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    marginTop: 12,
  },
  guestListItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  guestListName: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.primaryDark,
  },
  guestListSubText: {
    fontSize: 12,
    fontWeight: '400',
    color: '#64748b',
  },
  guestListMetaText: {
    fontSize: 11,
    color: '#94a3b8',
    marginTop: 2,
  },
  guestActionIconButton: {
    padding: 6,
    borderRadius: 6,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#f1f5f9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyGuestList: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  emptyGuestText: {
    fontSize: 16,
    color: colors.textSecondary,
  },
  guestPageContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  guestPageContent: {
    flex: 1,
    backgroundColor: '#f5f5f5',
    marginTop: 50,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  guestPageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  guestPageBackButton: {
    padding: 8,
    width: 40,
  },
  guestPageBackIcon: {
    fontSize: 24,
    color: colors.primaryDark,
  },
  guestPageTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.primaryDark,
    flex: 1,
    textAlign: 'center',
  },
  guestPageScroll: {
    flex: 1,
    padding: 16,
  },
  guestPageCard: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  guestPageCardContent: {
    padding: 16,
  },
  guestPageInfo: {
    marginBottom: 12,
  },
  guestPageName: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.primaryDark,
    marginBottom: 4,
  },
  guestPageId: {
    fontSize: 12,
    color: colors.textSecondary,
    marginBottom: 8,
  },
  guestPageEmail: {
    fontSize: 14,
    color: colors.textDark,
    marginBottom: 4,
  },
  guestPagePhone: {
    fontSize: 14,
    color: colors.textDark,
  },
  removeButton: {
    backgroundColor: '#dc3545',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 6,
    alignSelf: 'flex-end',
  },
  removeButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  emptyGuestsContainer: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  emptyGuestsText: {
    fontSize: 16,
    color: colors.textSecondary,
  },
  // Simple action buttons styles
  actionButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  simpleActionButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 6,
  },
  simpleActionButtonText: {
    fontSize: 13,
    fontWeight: '500',
    color: colors.primary,
    textAlign: 'center',
  },
  pageBodyTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.primaryDark,
    marginHorizontal: 16,
    marginTop: 10,
    marginBottom: 16,
    textAlign: 'left',
  },
  pageBodyTitleRTL: {
    fontFamily: 'System',
    textAlign: 'right',
  },
  removeGuestButton: {
    backgroundColor: '#dc3545',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeGuestButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
  },
  leaveGuestButton: {
    backgroundColor: '#fee2e2',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  leaveGuestButtonText: {
    color: '#dc2626',
    fontSize: 12,
    fontWeight: '600',
  },
});
