import { StyleSheet } from 'react-native';
import { colors, colorUtils } from '../../constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.backgroundCard,
    marginBottom: 40,
  },
  headerBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.primary,
    zIndex: 0,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: 'transparent',
    zIndex: 1,
  },
  headerRTL: {
    flexDirection: 'row-reverse',
  },
  backButton: {
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  backButtonRTL: {
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  backButtonText: {
    fontSize: 37,
    lineHeight: 28,
    color: colors.textWhite,
    fontWeight: '700',
    textAlign: 'center',
  },
  backButtonTextRTL: {
    fontFamily: 'System',
  },
  headerTitle: {
    fontSize: 19,
    fontWeight: '700',
    color: colors.textWhite,
    flex: 1,
    textAlign: 'center',
  },
  headerTitleRTL: {
    fontFamily: 'System',
  },
  headerSpacer: {
    width: 40,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 0,
    paddingHorizontal: 16,
    paddingBottom: 40,
  },
  section: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  iconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  iconText: {
    fontSize: 18,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textDark,
  },
  sectionTitleRTL: {
    fontFamily: 'System',
  },
  editButton: {
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: colors.primary,
    backgroundColor: 'transparent',
  },
  editIcon: {
    fontSize: 16,
    marginRight: 6,
  },
  editButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
  editButtonTextRTL: {
    fontFamily: 'System',
  },
  viewMode: {
    gap: 0,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
  },
  infoRowRTL: {
    flexDirection: 'row-reverse',
  },
  infoIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colorUtils.addOpacity(colors.primary, 0.08),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  infoIconContainerRTL: {
    marginRight: 0,
    marginLeft: 12,
  },
  infoContent: {
    flex: 1,
  },
  infoContentRTL: {
    alignItems: 'flex-end',
  },
  infoLabel: {
    fontSize: 12,
    color: colors.textSecondary,
    marginBottom: 4,
  },
  infoLabelRTL: {
    fontFamily: 'System',
    textAlign: 'right',
  },
  infoValue: {
    fontSize: 14.5,
    fontWeight: '600',
    color: colors.textDark,
  },
  infoValueRTL: {
    fontFamily: 'System',
    textAlign: 'right',
  },
  infoDivider: {
    height: 1,
    backgroundColor: '#E5E7EB',
    marginLeft: 48,
  },
  infoDividerRTL: {
    marginLeft: 0,
    marginRight: 48,
  },
  fieldRow: {
    flexDirection: 'column',
    gap: 14,
    marginBottom: 14,
  },
  fieldColumn: {
    width: '100%',
  },
  fieldSingle: {
    marginBottom: 0,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '500',
    color: colors.textSecondary,
    marginBottom: 6,
  },
  fieldLabelRTL: {
    fontFamily: 'System',
    textAlign: 'right',
  },
  fieldValue: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.textDark,
  },
  fieldValueRTL: {
    fontFamily: 'System',
  },
  editMode: {
    gap: 24,
  },
  centeredPhotoContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 10,
    width: '100%',
  },
  photoCircleWrapper: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoCircle: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: colorUtils.addOpacity(colors.primary, 0.08),
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: colors.primary,
  },
  photoImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  photoInitials: {
    fontSize: 30,
    fontWeight: '700',
    color: colors.primary,
  },
  cameraBadge: {
    position: 'absolute',
    bottom: 0,
    right: 2,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primary,
    borderWidth: 2.5,
    borderColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
  },
  removePhotoIcon: {
    position: 'absolute',
    top: 0,
    left: 2,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.error,
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
  },
  photoHint: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 10,
    textAlign: 'center',
  },
  photoHintRTL: {
    fontFamily: 'System',
  },
  formFieldsContainer: {
    gap: 16,
    width: '100%',
    marginVertical: 14,
  },
  formColumn: {
    width: '100%',
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textDark,
    marginBottom: 8,
  },
  inputLabelRTL: {
    fontFamily: 'System',
  },
  input: {
    backgroundColor: colors.backgroundLight,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    fontSize: 14,
    color: colors.textDark,
  },
  inputRTL: {
    textAlign: 'right',
    fontFamily: 'System',
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
    marginTop: 8,
  },
  cancelButton: {
    paddingVertical: 11,
    paddingHorizontal: 28,
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: colors.backgroundLight,
    height: 46,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.textDark,
  },
  cancelButtonTextRTL: {
    fontFamily: 'System',
  },
  saveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary,
    paddingVertical: 11,
    paddingHorizontal: 32,
    borderRadius: 24,
    gap: 8,
    height: 46,
    justifyContent: 'center',
  },
  saveIcon: {
    fontSize: 16,
  },
  saveButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textWhite,
  },
  saveButtonTextRTL: {
    fontFamily: 'System',
  },
  passwordInfo: {
    paddingVertical: 12,
  },
  passwordText: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
  },
  passwordTextRTL: {
    fontFamily: 'System',
  },
  settingsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  settingsCardInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  settingsCardInnerRTL: {
    flexDirection: 'row-reverse',
  },
  settingsIconContainer: {
    width: 42,
    height: 42,
    borderRadius: 21,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  settingsIconContainerRTL: {
    marginRight: 0,
    marginLeft: 12,
  },
  passwordIconBg: {
    backgroundColor: colorUtils.addOpacity(colors.primary, 0.08),
  },
  deleteIconBg: {
    backgroundColor: colorUtils.addOpacity(colors.error, 0.08),
  },
  settingsTextContainer: {
    flex: 1,
  },
  settingsTextContainerRTL: {
    alignItems: 'flex-end',
  },
  settingsTitle: {
    fontSize: 15.5,
    fontWeight: '700',
    color: colors.textDark,
    marginBottom: 2,
  },
  settingsTitleRTL: {
    fontFamily: 'System',
  },
  deleteTitleText: {
    color: colors.error,
  },
  settingsSubtitle: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  settingsSubtitleRTL: {
    fontFamily: 'System',
    textAlign: 'right',
  },
  sleekInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1.5,
    borderBottomColor: '#E5E7EB',
    paddingVertical: 4,
    width: '100%',
    marginTop: 2,
    marginBottom: 10,
  },
  sleekInputWrapperRTL: {
    flexDirection: 'row-reverse',
  },
  sleekInputWrapperActive: {
    borderBottomColor: colors.primary,
  },
  sleekInputIcon: {
    marginRight: 8,
  },
  sleekInputIconRTL: {
    marginRight: 0,
    marginLeft: 8,
  },
  sleekInputDivider: {
    width: 1,
    height: 16,
    backgroundColor: '#E5E7EB',
    marginRight: 10,
  },
  sleekInputDividerRTL: {
    marginRight: 0,
    marginLeft: 10,
  },
  sleekTextInput: {
    flex: 1,
    fontSize: 14.5,
    color: colors.textDark,
    paddingVertical: 6,
    textAlign: 'left',
  },
  sleekTextInputRTL: {
    textAlign: 'right',
  },
  phoneInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    width: '100%',
  },
  countryCodeWrapper: {
    width: 75,
    height: 42,
    borderBottomWidth: 1.5,
    borderBottomColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
    marginBottom: 10,
  },
  countryCodeWrapperActive: {
    borderBottomColor: colors.primary,
  },
  countryCodeInput: {
    fontSize: 14.5,
    color: colors.textDark,
    fontWeight: '600',
    textAlign: 'center',
    padding: 0,
    width: '100%',
  },
  profileHeaderBlock: {
    height: 50,
    backgroundColor: colors.primary,
    position: 'relative',
    overflow: 'hidden',
    marginLeft: -16,
    marginRight: -16,
  },
  topographicSvg: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  profileCurveDivider: {
    height: 30,
    backgroundColor: colors.primary,
    marginTop: -1,
    marginLeft: -16,
    marginRight: -16,
    marginBottom: 20,
  },
  headerOverlayBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    backgroundColor: 'transparent',
    zIndex: 1,
  },
  headerOverlayBarRTL: {
    flexDirection: 'row-reverse',
  },
  headerBackButtonCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pageBodyTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.primaryDark,
    marginHorizontal: 16,
    marginTop: 10,
    marginBottom: 16,
    textAlign: 'left',
  },
  pageBodyTitleRTL: {
    fontFamily: 'System',
    textAlign: 'right',
  },
});
