import { StyleSheet } from 'react-native';
import { colors, colorUtils } from '../../constants/colors';

export const styles = StyleSheet.create({
  addressesContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    flexGrow: 1,
    padding: 16,
    paddingBottom: 140,
  },
  headerBar: {
    backgroundColor: 'transparent',
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    zIndex: 1,
  },
  headerBarRTL: {
    flexDirection: 'row-reverse',
  },
  headerBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.primary,
    zIndex: 0,
  },
  headerBackButton: {
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  headerBackIcon: {
    color: colors.textWhite,
    fontSize: 37,
    lineHeight: 28,
    textAlign: 'center',
    fontWeight: '700',
  },
  headerBackTextRTL: {
    fontFamily: 'System',
  },
  headerTitle: {
    fontSize: 19,
    fontWeight: '700',
    color: colors.textWhite,
    flex: 1,
    textAlign: 'center',
  },
  headerTitleRTL: {
    fontFamily: 'System',
  },
  headerAddButton: {
    paddingVertical: 8,
    paddingHorizontal: 4,
    minWidth: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerAddButtonText: {
    color: colors.textWhite,
    fontSize: 16,
    fontWeight: '600',
  },

  emptyBox: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 40,
    minHeight: 340,
  },
  emptyIconWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colorUtils.addOpacity(colors.primary, 0.08),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colorUtils.addOpacity(colors.primary, 0.15),
  },
  emptyIcon: {
    color: colors.primary,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textDark,
    marginBottom: 8,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 20,
    paddingHorizontal: 16,
  },

  primaryButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 24,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
  },
  primaryButtonText: {
    color: colors.textWhite,
    fontWeight: '700',
    fontSize: 15,
  },

  formContainer: {
    marginTop: 16,
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.borderMedium,
    borderRadius: 6,
    padding: 10,
    marginBottom: 8,
  },
  formButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  secondaryButton: {
    padding: 10,
    backgroundColor: colors.background,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.borderMedium,
  },
  secondaryButtonText: { color: colors.textDark },
  primaryButtonSmall: {
    backgroundColor: colors.primary,
    padding: 10,
    borderRadius: 6,
  },
  primaryButtonTextSmall: { color: colors.textWhite, fontWeight: '700' },

  // Redesigned Address Card - Compact, Premium & Clean
  addressCard: {
    backgroundColor: '#FFFFFF',
    padding: 14,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  addressCardInner: {
    padding: 0,
  },
  addressCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  addressCardHeaderRTL: {
    flexDirection: 'row-reverse',
  },
  addressHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  addressHeaderLeftRTL: {
    flexDirection: 'row-reverse',
  },
  addressIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: colorUtils.addOpacity(colors.primary, 0.08),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  addressIconContainerRTL: {
    marginRight: 0,
    marginLeft: 8,
  },
  addressNameSection: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
    flex: 1,
  },
  addressNameSectionRTL: {
    flexDirection: 'row-reverse',
  },
  addressName: {
    fontWeight: '700',
    fontSize: 15,
    color: colors.textDark,
  },
  addressNameRTL: {
    textAlign: 'right',
  },
  addressActionButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  addressActionButtonsRTL: {
    flexDirection: 'row-reverse',
  },
  cardIconButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  editIconButton: {
    backgroundColor: colorUtils.addOpacity(colors.primary, 0.06),
  },
  deleteIconButton: {
    backgroundColor: colorUtils.addOpacity(colors.error, 0.06),
  },
  defaultBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: colorUtils.addOpacity(colors.success || '#10B981', 0.1),
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colorUtils.addOpacity(colors.success || '#10B981', 0.2),
  },
  defaultBadgeText: {
    color: colors.success || '#10B981',
    fontSize: 10,
    fontWeight: '600',
  },
  addressDetailsContainer: {
    marginTop: 2,
    paddingLeft: 40, // align with text start
  },
  addressDetailsContainerRTL: {
    paddingLeft: 0,
    paddingRight: 40,
    alignItems: 'flex-end',
  },
  addressLineWithIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  addressLineWithIconRTL: {
    flexDirection: 'row-reverse',
  },
  addressLineText: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    marginLeft: 6,
    flex: 1,
  },
  addressLineTextRTL: {
    marginLeft: 0,
    marginRight: 6,
    textAlign: 'right',
  },
  setDefaultContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 6,
  },
  setDefaultContainerRTL: {
    justifyContent: 'flex-start',
  },
  setDefaultLink: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: colorUtils.addOpacity(colors.primary, 0.06),
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colorUtils.addOpacity(colors.primary, 0.12),
  },
  setDefaultLinkText: {
    color: colors.primary,
    fontWeight: '600',
    fontSize: 11,
  },
  headerLeftRow: { flexDirection: 'row', alignItems: 'center' },
  headerLeftRowRTL: {
    flexDirection: 'row-reverse',
  },
  // Bigger back icon/button with colored background
  backButtonInline: {
    marginRight: 12,
    width: 36,
    height: 36,
    padding: 0,
    borderRadius: 18,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonInlineRTL: {
    marginRight: 0,
    marginLeft: 12,
  },
  backButtonTextInline: {
    color: colors.textWhite,
    fontSize: 28,
    fontWeight: '700',
    lineHeight: 28,
    textAlign: 'center',
  },
  headerRowRTL: {
    flexDirection: 'row-reverse',
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    width: '100%',
    maxHeight: '85%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 10,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: '#FFFFFF',
  },
  modalHeaderRTL: {
    flexDirection: 'row-reverse',
  },
  modalCloseButton: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textDark,
  },
  modalBody: {
    paddingHorizontal: 20,
    paddingTop: 20,
    maxHeight: 480,
  },
  modalInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    paddingHorizontal: 12,
    marginBottom: 12,
    height: 48,
  },
  modalInputWrapperRTL: {
    flexDirection: 'row-reverse',
  },
  modalInputWrapperActive: {
    borderColor: colors.primary,
    backgroundColor: '#FFFFFF',
  },
  modalInputIcon: {
    marginRight: 10,
  },
  modalInputIconRTL: {
    marginRight: 0,
    marginLeft: 10,
  },
  modalInputDivider: {
    width: 1,
    height: 18,
    backgroundColor: '#E2E8F0',
    marginRight: 12,
  },
  modalInputDividerRTL: {
    marginRight: 0,
    marginLeft: 12,
  },
  modalTextInput: {
    flex: 1,
    fontSize: 14.5,
    color: colors.textDark,
    paddingVertical: 8,
    textAlign: 'left',
  },
  modalTextInputRTL: {
    textAlign: 'right',
    fontFamily: 'System',
  },
  modalButtonsRow: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: colors.border,
    padding: 16,
    gap: 12,
  },
  modalButtonsRowRTL: {
    flexDirection: 'row-reverse',
  },
  modalSecondaryButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5F5F5',
    borderWidth: 1.5,
    borderColor: colors.borderMedium,
  },
  modalSecondaryButtonText: {
    color: colors.textDark,
    fontWeight: '600',
  },
  modalPrimaryButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  modalPrimaryButtonText: {
    color: colors.textWhite,
    fontWeight: '700',
  },
  profileHeaderBlock: {
    height: 50,
    backgroundColor: colors.primary,
    position: 'relative',
    overflow: 'hidden',
  },
  topographicSvg: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  profileCurveDivider: {
    height: 30,
    backgroundColor: colors.primary,
    marginTop: -1,
  },
  headerOverlayBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    backgroundColor: 'transparent',
    zIndex: 1,
  },
  headerOverlayBarRTL: {
    flexDirection: 'row-reverse',
  },
  headerBackButtonCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerSpacer: {
    width: 40,
  },
  bottomAddButton: {
    backgroundColor: colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 10,
    marginBottom: 20,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 4,
  },
  bottomAddButtonText: {
    color: colors.textWhite,
    fontSize: 16,
    fontWeight: '700',
    marginHorizontal: 8,
  },
  pageBodyTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.primaryDark,
    marginHorizontal: 16,
    marginTop: 10,
    marginBottom: 16,
    textAlign: 'left',
  },
  pageBodyTitleRTL: {
    fontFamily: 'System',
    textAlign: 'right',
  },
  pageHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginTop: 10,
    marginBottom: 16,
  },
  pageHeaderRowRTL: {
    flexDirection: 'row-reverse',
  },
  topAddButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colorUtils.addOpacity(colors.primary, 0.08),
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colorUtils.addOpacity(colors.primary, 0.15),
  },
  topAddButtonText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '700',
    marginHorizontal: 4,
  },
  pageBodyTitleInline: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.primaryDark,
    textAlign: 'left',
  },
  pageBodyTitleInlineRTL: {
    fontFamily: 'System',
    textAlign: 'right',
  },
  setDefaultBadgeInline: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: colorUtils.addOpacity(colors.primary, 0.06),
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colorUtils.addOpacity(colors.primary, 0.15),
  },
  setDefaultBadgeInlineText: {
    color: colors.primary,
    fontSize: 10,
    fontWeight: '600',
  },
});

export default styles;
