import { StyleSheet } from 'react-native';
import { colors } from '../../constants/colors';

export const styles = StyleSheet.create({
  fullPageContainer: {
    flex: 1,
    backgroundColor: colors.backgroundCard,
    position: 'relative',
  },
  headerBar: {
    backgroundColor: 'transparent',
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    zIndex: 1,
  },
  headerBarRTL: {
    flexDirection: 'row-reverse',
  },
  headerBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.primary,
    zIndex: 0,
  },
  headerBackButton: {
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  headerBackText: {
    fontSize: 16,
    color: colors.textWhite,
    fontWeight: '500',
  },
  // headerBackInline: {
  //   width: 40,
  //   height: 40,
  //   borderRadius: 20,
  //   backgroundColor: colors.textWhite,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   marginRight: 8,
  // },
  headerBackIcon: {
    color: colors.textWhite,
    // smaller font and explicit lineHeight to center the chevron glyph exactly inside the 40x40 circle
    fontSize: 37,
    lineHeight: 28,
    textAlign: 'center',
    fontWeight: '700',
  },
  headerBackTextRTL: {
    fontFamily: 'System',
  },
  headerTitle: {
    fontSize: 19,
    fontWeight: '700',
    color: colors.textWhite,
    flex: 1,
    textAlign: 'center',
  },
  headerTitleRTL: {
    fontFamily: 'System',
  },
  // spacer width matches back button width so title remains visually centered
  headerSpacer: {
    width: 40,
  },
  scrollContainer: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: colors.backgroundLight,
  },
  contentContainer: {
    paddingTop: 0,
    paddingBottom: 80,
  },
  userInfoSection: {
    backgroundColor: 'transparent',
    paddingTop: 0,
    paddingBottom: 24,
    paddingHorizontal: 20,
    alignItems: 'center',
    marginBottom: 0,
  },
  userInfoRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  userDataContainer: {
    flex: 1,
    marginLeft: 16,
    justifyContent: 'center',
  },
  profileImageContainer: {
    marginTop: -50,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  profileImagePlaceholder: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: colors.primaryDark,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  profileImagePlaceholderText: {
    fontSize: 40,
    fontWeight: '700',
    color: colors.textWhite,
    textAlign: 'center',
  },
  profilePlaceholder: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#D3D3D3',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileIcon: {
    width: 50,
    height: 50,
    tintColor: '#666',
  },
  userName: {
    fontSize: 20,
    fontWeight: '600',
    color: colors.textDark,
    marginBottom: 8,
  },
  userNameRTL: {
    fontFamily: 'System',
  },
  userPhone: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  userPhoneRTL: {
    fontFamily: 'System',
  },
  noPhone: {
    fontSize: 14,
    color: '#999',
    fontStyle: 'italic',
  },
  noPhoneRTL: {
    fontFamily: 'System',
  },
  menuSection: {
    paddingHorizontal: 16,
  },
  menuItem: {
    backgroundColor: colors.backgroundLight,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    paddingVertical: 18,
    paddingHorizontal: 20,
    marginBottom: 12,
    borderRadius: 15,
  },
  menuItemPrimary: {
    backgroundColor: colors.primary,
  },
  menuText: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.textDark,
    textAlign: 'center',
  },
  menuTextRTL: {
    fontFamily: 'System',
  },
  menuTextWhite: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  menuTextWhiteRTL: {
    fontFamily: 'System',
  },
  menuTextLogout: {
    fontSize: 16,
    fontWeight: '600',
    color: '#E53935',
    textAlign: 'center',
  },
  menuTextLogoutRTL: {
    fontFamily: 'System',
  },
  backButton: {
    marginTop: 20,
    marginHorizontal: 16,
    paddingVertical: 12,
    alignItems: 'center',
  },
  backButtonText: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '500',
  },
  backButtonTextRTL: {
    fontFamily: 'System',
  },
  loginPromptContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 30,
    paddingTop: 60,
  },
  loginPromptTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: colors.textDark,
    marginTop: 20,
    marginBottom: 12,
  },
  loginPromptTitleRTL: {
    fontFamily: 'System',
  },
  loginPromptText: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: 30,
  },
  loginPromptTextRTL: {
    fontFamily: 'System',
  },
  loginButton: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    paddingHorizontal: 40,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  loginButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  menuContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
    marginBottom: 16,
    marginHorizontal: 16,
  },
  logoutCardContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
    marginBottom: 16,
    marginHorizontal: 16,
  },
  menuItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: '#FFFFFF',
  },
  menuItemRowRTL: {
    flexDirection: 'row-reverse',
  },
  menuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  menuItemLeftRTL: {
    flexDirection: 'row-reverse',
    gap: 12,
  },
  menuItemText: {
    fontSize: 15,
    fontWeight: '500',
    color: '#2D3748',
  },
  menuItemTextRTL: {
    fontFamily: 'System',
  },
  menuItemTextLogout: {
    fontSize: 15,
    fontWeight: '600',
    color: '#E53935',
  },
  menuItemTextLogoutRTL: {
    fontFamily: 'System',
  },
  menuDivider: {
    height: 1,
    backgroundColor: '#EDF2F7',
    marginHorizontal: 20,
  },
  userNameCentered: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.primaryDark,
    marginBottom: 4,
    textAlign: 'center',
  },
  userNameCenteredRTL: {
    fontFamily: 'System',
  },
  userEmailCentered: {
    fontSize: 14.5,
    color: colors.textSecondary,
    marginBottom: 8,
    textAlign: 'center',
  },
  userEmailCenteredRTL: {
    fontFamily: 'System',
  },
  userLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 2,
  },
  userLocationRowRTL: {
    flexDirection: 'row-reverse',
  },
  userLocationText: {
    fontSize: 14,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  userLocationTextRTL: {
    fontFamily: 'System',
  },
  profileHeaderBlock: {
    height: 140,
    backgroundColor: colors.primary,
    position: 'relative',
    overflow: 'hidden',
  },
  topographicSvg: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  profileCurveDivider: {
    height: 40,
    backgroundColor: colors.primary,
    marginTop: -1,
  },
  headerOverlayBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    backgroundColor: 'transparent',
    zIndex: 1,
  },
  headerOverlayBarRTL: {
    flexDirection: 'row-reverse',
  },
  headerBackButtonCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
