import { StyleSheet } from 'react-native';
import { colors } from '../../constants/colors';

export const styles = StyleSheet.create({
  fullPageContainer: {
    flex: 1,
    backgroundColor: colors.backgroundCard,
    position: 'relative',
  },
  primaryFlexContainer: {
    flex: 1,
    backgroundColor: colors.backgroundCard,
  },
  headerBar: {
    backgroundColor: 'transparent',
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    zIndex: 1,
  },
  headerBarRTL: {
    flexDirection: 'row-reverse',
  },
  headerBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.backgroundCard,
    zIndex: 0,
  },
  headerBackButton: {
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  headerBackText: {
    fontSize: 16,
    color: '#0F172A',
    fontWeight: '500',
  },
  headerBackIcon: {
    color: '#0F172A',
    fontSize: 37,
    lineHeight: 28,
    textAlign: 'center',
    fontWeight: '700',
  },
  headerBackTextRTL: {
    fontFamily: 'System',
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#0F172A',
    flex: 1,
    textAlign: 'left',
  },
  headerTitleRTL: {
    fontFamily: 'System',
    textAlign: 'right',
  },
  headerSpacer: {
    width: 42,
  },
  scrollContainer: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: colors.backgroundCard,
  },
  contentContainer: {
    paddingTop: 0,
    paddingBottom: 90,
  },
  cleanHeaderBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: 'transparent',
    zIndex: 2,
  },
  cleanHeaderBarRTL: {
    flexDirection: 'row-reverse',
  },
  headerBackButtonCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  positionRelative: {
    position: 'relative',
  },
  notificationBadge: {
    position: 'absolute',
    top: 7,
    right: 7,
    width: 9,
    height: 9,
    borderRadius: 4.5,
    backgroundColor: '#EF4444',
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },
  /* Floating Profile Card & User Info */
  userInfoSection: {
    paddingHorizontal: 16,
    marginTop: 48,
    marginBottom: 20,
    alignItems: 'center',
  },
  profileCardFloating: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 56,
    paddingBottom: 22,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 14,
    elevation: 3,
    position: 'relative',
    borderWidth: 1,
    borderColor: 'rgba(241, 245, 249, 0.8)',
  },
  avatarWrapperAbsolute: {
    position: 'absolute',
    top: -44,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 5,
  },
  avatarOuterRing: {
    width: 94,
    height: 94,
    borderRadius: 47,
    borderWidth: 2,
    borderColor: 'rgba(0, 161, 156, 0.25)',
    padding: 3,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#00a19c',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  avatarInnerRing: {
    width: 84,
    height: 84,
    borderRadius: 42,
    borderWidth: 3,
    borderColor: '#FFFFFF',
    overflow: 'hidden',
    backgroundColor: colors.primaryDark,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileImage: {
    width: 84,
    height: 84,
    borderRadius: 42,
  },
  profileImagePlaceholder: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: colors.primaryDark,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileImagePlaceholderText: {
    fontSize: 34,
    fontWeight: '700',
    color: colors.textWhite,
    textAlign: 'center',
  },
  userNameCentered: {
    fontSize: 21,
    fontWeight: '700',
    color: '#0F172A',
    marginBottom: 3,
    textAlign: 'center',
  },
  userNameCenteredRTL: {
    fontFamily: 'System',
  },
  userEmailCentered: {
    fontSize: 13.5,
    color: '#64748B',
    marginBottom: 10,
    textAlign: 'center',
  },
  userEmailCenteredRTL: {
    fontFamily: 'System',
  },
  userLocationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0FDFA',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    gap: 6,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#CCFBF1',
  },
  userLocationBadgeRTL: {
    flexDirection: 'row-reverse',
  },
  userLocationText: {
    fontSize: 12.5,
    color: colors.primary,
    fontWeight: '600',
  },
  userLocationTextRTL: {
    fontFamily: 'System',
  },
  /* Stats row inside Floating User Card */
  statsContainer: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 4,
    marginBottom: 14,
  },
  statsContainerRTL: {
    flexDirection: 'row-reverse',
  },
  statBox: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 6,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  statNumber: {
    fontSize: 17,
    fontWeight: '700',
    color: '#0F172A',
    marginBottom: 2,
  },
  statLabel: {
    fontSize: 11.5,
    color: '#64748B',
    fontWeight: '600',
  },
  statLabelRTL: {
    fontFamily: 'System',
  },
  /* Feature Banner inside Floating User Card */
  promoBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#0F172A',
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 14,
    width: '100%',
  },
  promoBannerRTL: {
    flexDirection: 'row-reverse',
  },
  promoBannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  promoBannerLeftRTL: {
    flexDirection: 'row-reverse',
  },
  promoIconBox: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  promoTextContainer: {
    flex: 1,
  },
  promoTitle: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  promoSubtitle: {
    fontSize: 10.5,
    color: '#94A3B8',
    marginTop: 1,
  },
  promoBtn: {
    backgroundColor: colors.primary,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  promoBtnText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  /* Section Title & Menu List */
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 16,
    marginTop: 4,
    marginBottom: 10,
  },
  sectionHeaderRowRTL: {
    flexDirection: 'row-reverse',
  },
  pageBodyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0F172A',
  },
  pageBodyTitleRTL: {
    fontFamily: 'System',
    textAlign: 'right',
  },
  menuSection: {
    paddingHorizontal: 0,
  },
  menuContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    marginHorizontal: 16,
    marginBottom: 14,
    paddingVertical: 4,
    shadowColor: '#004d49',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: 'rgba(241, 245, 249, 0.8)',
    overflow: 'hidden',
  },
  menuItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 13,
    paddingHorizontal: 16,
    backgroundColor: '#FFFFFF',
  },
  menuItemRowRTL: {
    flexDirection: 'row-reverse',
  },
  menuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  menuItemLeftRTL: {
    flexDirection: 'row-reverse',
    gap: 12,
  },
  menuIconWrapper: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: '#F0FDFA',
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuItemText: {
    fontSize: 14.5,
    fontWeight: '600',
    color: '#1E293B',
  },
  menuItemTextRTL: {
    fontFamily: 'System',
  },
  menuDivider: {
    height: 1,
    backgroundColor: '#F1F5F9',
    marginHorizontal: 16,
  },
  /* Logout Separate Card Container */
  logoutCardContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    marginHorizontal: 16,
    marginBottom: 20,
    paddingVertical: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
    borderWidth: 1,
    borderColor: 'rgba(241, 245, 249, 0.8)',
    overflow: 'hidden',
  },
  logoutIconWrapper: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: '#FEF2F2',
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuItemTextLogout: {
    fontSize: 14.5,
    fontWeight: '700',
    color: '#EF4444',
  },
  menuItemTextLogoutRTL: {
    fontFamily: 'System',
  },
  /* Guest / Login Prompt View */
  loginPromptContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: -45,
  },
  profilePlaceholderLogin: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileIcon: {
    width: 44,
    height: 44,
    tintColor: '#64748B',
  },
  loginPromptTitleBold: {
    fontSize: 22,
    fontWeight: '700',
    color: '#0F172A',
    marginTop: 14,
    marginBottom: 8,
    textAlign: 'center',
  },
  loginPromptTitleRTL: {
    fontFamily: 'System',
  },
  loginPromptText: {
    fontSize: 14,
    color: '#64748B',
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 20,
  },
  loginPromptTextRTL: {
    fontFamily: 'System',
  },
  loginButtonRounded: {
    backgroundColor: colors.primary,
    paddingHorizontal: 36,
    borderRadius: 24,
    height: 46,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  loginButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },

});

export const notifStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'flex-end',
  },
  container: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    height: '80%',
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 10,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  headerRTL: {
    flexDirection: 'row-reverse',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0f172a',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  headerActionsRTL: {
    flexDirection: 'row-reverse',
  },
  clearButton: {
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  clearButtonText: {
    fontSize: 14,
    color: '#ef4444',
    fontWeight: '600',
  },
  closeButton: {
    padding: 4,
  },
  iconMarginRTL: {
    marginLeft: 12,
  },
  iconMarginLTR: {
    marginRight: 12,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 40,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 80,
  },
  emptyText: {
    marginTop: 16,
    fontSize: 15,
    color: '#64748b',
    fontWeight: '500',
  },
  card: {
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  cardRTL: {
    flexDirection: 'row-reverse',
  },
  unreadCard: {
    backgroundColor: '#f8fafc',
    borderColor: '#e2e8f0',
  },
  cardIconContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardTextContainer: {
    flex: 1,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  cardHeaderRowRTL: {
    flexDirection: 'row-reverse',
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#334155',
  },
  unreadText: {
    fontWeight: '700',
    color: '#0f172a',
  },
  unreadDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#3b82f6',
  },
  cardMessage: {
    fontSize: 13,
    color: '#64748b',
    lineHeight: 18,
    marginBottom: 6,
  },
  cardTime: {
    fontSize: 10,
    color: '#94a3b8',
  },
  textRight: {
    textAlign: 'right',
  },
});
