import { StyleSheet } from 'react-native';
import { colors } from '../../constants/colors';

export const createStyles = (SCREEN_WIDTH: number) => {
  const isTablet = SCREEN_WIDTH >= 600;
  const carouselHeight = isTablet ? 500 : 380;
  
  return StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    height: '100%',
  },
  actionsRow: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.backgroundLight,
  },
  fixedActionsRow: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: colors.backgroundLight,
    zIndex: 50,
    borderRadius: 0,
  },
  actionsLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  actionsRight: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 14,
  },
  actionButton: {
    width: 44,
    height: 44,
    borderRadius: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionButtonLarge: {
    width: 52,
    height: 52,
    borderRadius: 0,
  },
  actionIcon: {
    fontSize: 20,
    color: colors.primary,
    fontWeight: '600',
  },
  backButton: {
    position: 'absolute',
    top: 50,
    left: 16,
    zIndex: 10,
    width: 40,
    height: 40,
    borderRadius: 0,
    backgroundColor: colors.backgroundLight,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  backIcon: {
    fontSize: 24,
    color: colors.primary,
    fontWeight: '600',
  },
  favoriteButton: {
    position: 'absolute',
    top: 50,
    right: 60,
    zIndex: 10,
    width: 40,
    height: 40,
    borderRadius: 0,
    backgroundColor: colors.backgroundLight,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  favoriteIcon: {
    fontSize: 22,
    color: colors.primary,
  },
  shareButton: {
    position: 'absolute',
    top: 50,
    right: 16,
    zIndex: 10,
    width: 40,
    height: 40,
    borderRadius: 0,
    backgroundColor: colors.backgroundLight,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  shareIcon: {
    fontSize: 20,
    color: colors.primary,
  },
  carouselContainer: {
    width: SCREEN_WIDTH,
    height: carouselHeight,
    position: 'relative',
  },
  imageSlide: {
    width: SCREEN_WIDTH,
    height: carouselHeight,
    position: 'relative',
  },
  carouselImage: {
    width: '100%',
    height: '100%',
  },
  imageDiscountBadge: {
    position: 'absolute',
    top: 16,
    right: 16,
    backgroundColor: colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 6,
  },
  imageDiscountText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  paginationContainer: {
    position: 'absolute',
    bottom: 16,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  paginationDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.primaryLight,
  },
  paginationDotActive: {
    backgroundColor: colors.primary,
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  infoSection: {
    backgroundColor: colors.background,
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  serviceName: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.primary,
    marginBottom: 4,
  },
  serviceNameRTL: {
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  vendorName: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.textSecondary,
    marginBottom: 12,
  },
  vendorNameRTL: {
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  priceBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    marginTop: 8,
  },
  priceLabel: {
    fontSize: 11,
    color: colors.textSecondary,
    marginBottom: 2,
  },
  priceValue: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.primary,
  },
  priceUnit: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textSecondary,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  ratingStars: {
    fontSize: 14,
    color: colors.primary,
    letterSpacing: 1,
  },
  ratingText: {
    fontSize: 11,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  descriptionText: {
    fontSize: 14,
    lineHeight: 21,
    color: '#666',
    marginBottom: 16,
    backgroundColor: colors.backgroundCard,
    padding: 16,
    borderRadius: 12,
  },
  descriptionTextRTL: {
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  policiesSection: {
    marginTop: 4,
    marginBottom: 12,
    paddingTop: 20,
    paddingHorizontal: 0,
    paddingBottom: 20,
    backgroundColor: colors.backgroundCard,
    borderRadius: 8,
  },
  policiesTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
    letterSpacing: 1.5,
    marginBottom: 16,
    textAlign: 'center',
    paddingHorizontal: 20,
  },
  policiesTitleRTL: {
    textAlign: 'right',
    letterSpacing: 0,
  },
  policiesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    rowGap: 16,
  },
  policyCard: {
    width: '48%',
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: 0,
  },
  policyCardRTL: {
    flexDirection: 'row-reverse',
  },
  policyIconContainer: {
    width: 40,
    height: 40,
    marginRight: 12,
    flexShrink: 0,
  },
  policyIconContainerRTL: {
    marginRight: 0,
    marginLeft: 12,
  },
  policyIcon: {
    width: '100%',
    height: '100%',
    tintColor: colors.primary,
  },
  policyIconPlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: 'transparent',
    borderRadius: 20,
    borderWidth: 1.4,
    borderColor: colors.primary,
  },
  policyContent: {
    flex: 1,
  },
  policyName: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.primary,
    marginBottom: 4,
  },
  policyNameRTL: {
    writingDirection: 'rtl',
    textAlign: 'right',
  },
  policyDescription: {
    fontSize: 11,
    color: '#666',
    lineHeight: 16,
  },
  policyDescriptionRTL: {
    writingDirection: 'rtl',
    textAlign: 'right',
  },

  /* Booking / availability preview: match vendor policy card width and style */
  bookingContainer: {
    backgroundColor: colors.backgroundCard,
    borderRadius: 8,
    paddingHorizontal: 20,
    paddingVertical: 14,
    marginTop: 0,
    marginBottom: 20,
  },
  bookingHeader: {
    alignSelf: 'center',
    backgroundColor: colors.background,
    color: colors.primary,
    fontSize: 12,
    fontWeight: '700',
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 12,
    marginBottom: 12,
    letterSpacing: 0.6,
  },
  bookingCard: {
    width: '100%',
    backgroundColor: 'transparent',
    borderRadius: 8,
    paddingBottom: 6,
  },
  bookingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.backgroundLight,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 10,
  },
  bookingRowRTL: {
    flexDirection: 'row-reverse',
  },
  bookingIconWrap: {
    marginRight: 16,
  },
  bookingIconWrapRTL: {
    marginRight: 0,
    marginLeft: 16,
  },
  calendarIconSmallBorder: {
    width: 36,
    height: 36,
    borderRadius: 8,
    borderWidth: 1.4,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  clockIconSmallBorder: {
    width: 36,
    height: 36,
    borderRadius: 8,
    borderWidth: 1.4,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookingText: {
    flex: 1,
    fontSize: 15,
    color: colors.textDark,
    fontWeight: '500',
  },
  availabilityButton: {
    alignSelf: 'center',
    backgroundColor: colors.primaryDark,
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 22,
    marginTop: 4,
  },
  availabilityButtonText: {
    color: colors.textWhite,
    fontSize: 14,
    fontWeight: '700',
  },
  addOptionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.backgroundLight,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginTop: 10,
  },
  addOptionText: {
    fontSize: 15,
    color: colors.textDark,
    fontWeight: '500',
  },

  /* Custom Text Section - isolated header */
  customTextContainer: {
    backgroundColor: colors.backgroundCard,
    borderRadius: 8,
    paddingHorizontal: 20,
    paddingVertical: 14,
    marginTop: 12,
    marginBottom: 0,
  },
  customTextHeader: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.primary,
    letterSpacing: 0.6,
    marginBottom: 12,
    textAlign: 'center',
    alignSelf: 'center',
    backgroundColor: colors.background,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 12,
  },

  optionGroupTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textDark,
    marginBottom: 10,
    marginTop: 4,
  },

  optionCardContainer: {
    // backgroundColor: '#FFFFFF',
    // borderRadius: 8,
    // borderWidth: 1,
    // borderColor: '#E0E0E0',
    marginBottom: 12,
    // overflow: 'hidden',
  },

  optionExpandedContent: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    //   backgroundColor: '#F9F9F9',
    //   borderTopWidth: 1,
    //   borderTopColor: '#E0E0E0',
  },

  /* Custom Inputs Section */
  textInputField: {
    borderWidth: 1,
    borderColor: colors.borderMedium,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 14,
    color: colors.textDark,
    backgroundColor: colors.backgroundLight,
    marginBottom: 8,
  },

  textInputFieldRTL: {
    fontFamily: 'System',
  },

  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: colors.backgroundLight,
    marginBottom: 8,
  },
  optionRowSelected: {
    backgroundColor: colors.primaryLight,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: colors.borderMedium,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  checkboxSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  optionText: {
    fontSize: 14,
    color: colors.textDark,
    flex: 1,
  },
  optionTextSelected: {
    fontWeight: '600',
    color: colors.primary,
  },
  optionPrice: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textSecondary,
    marginLeft: 12,
  },
  optionPriceSelected: {
    color: colors.primary,
  },

  /* Bottom Action Buttons */
  bottomActions: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.background,
    paddingHorizontal: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  addToCartButton: {
    backgroundColor: colors.primaryDark,
    borderRadius: 12,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  addToCartButtonText: {
    color: colors.textWhite,
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  backButtonBottom: {
    backgroundColor: 'transparent',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: colors.primary,
  },
  backButtonText: {
    color: colors.primary,
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  // Reviews Section Styles
  reviewsSection: {
    marginTop: 20,
    marginBottom: 16,
  },
  reviewsTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 16,
  },
  reviewsTitleRTL: {
    textAlign: 'right',
    fontFamily: 'Arial',
  },
  reviewStatsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    marginBottom: 16,
  },
  averageRatingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderRightColor: colors.border,
    paddingRight: 16,
  },
  averageRatingNumber: {
    fontSize: 36,
    fontWeight: '700',
    color: colors.primary,
  },
  averageRatingStars: {
    fontSize: 18,
    color: colors.primary,
    marginVertical: 4,
  },
  averageRatingText: {
    fontSize: 12,
    color: '#666',
  },
  ratingDistribution: {
    flex: 2,
    paddingLeft: 16,
  },
  distributionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  distributionStar: {
    width: 30,
    fontSize: 12,
    color: '#666',
  },
  distributionBar: {
    flex: 1,
    height: 8,
    backgroundColor: colors.border,
    borderRadius: 4,
    marginHorizontal: 8,
    overflow: 'hidden',
  },
  distributionFill: {
    height: '100%',
    backgroundColor: colors.primary,
  },
  distributionCount: {
    width: 30,
    fontSize: 12,
    color: '#666',
    textAlign: 'right',
  },
  reviewsList: {
    gap: 12,
  },
  reviewCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
  },
  reviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  reviewUserInfo: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flex: 1,
    gap: 12,
    marginRight: 12,
  },
  reviewUserAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  reviewUserAvatarPlaceholder: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  reviewUserAvatarText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '600',
  },
  reviewUserName: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textPrimary,
    flex: 1,
  },
  verifiedBadge: {
    fontSize: 11,
    color: colors.success,
    marginTop: 2,
  },
  reviewRating: {
    backgroundColor: colors.primaryLight,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  reviewRatingText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.primary,
  },
  reviewComment: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
    marginBottom: 8,
  },
  reviewCommentRTL: {
    textAlign: 'right',
    fontFamily: 'Arial',
  },
  reviewDate: {
    fontSize: 12,
    color: '#999',
  },
  vendorReply: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
  },
  vendorReplyLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.primary,
    marginBottom: 4,
  },
  vendorReplyText: {
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 18,
  },
  vendorReplyTextRTL: {
    textAlign: 'right',
    fontFamily: 'Arial',
  },
  showMoreReviewsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 24,
    backgroundColor: colors.backgroundLight,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: colors.primary,
    marginTop: 16,
    marginHorizontal: 16,
  },
  showMoreReviewsText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.primary,
    letterSpacing: 0.3,
  },
  });
};
